# Generated by Django 3.2.8 on 2021-10-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MF', 'Meat And Fish')], default='MF', max_length=5),
            preserve_default=False,
        ),
    ]
