# Generated by Django 3.2.8 on 2021-11-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='NONE', max_length=1000, upload_to='images/'),
            preserve_default=False,
        ),
    ]
