# Generated by Django 3.2.8 on 2021-11-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('', 'Please Select'), ('MF', 'Meat and Fish'), ('VEG', 'Fruit and Vegetables')], default='', max_length=5),
        ),
    ]
